# file: .travis.yml
language: objective-c
before_install:
	- brew update
	- brew install xctool

script:
	- xctool -workspace IT-Ebooks.xcworkspace -scheme IT-Ebooks
  	- xctool test -workspace IT-Ebooks.xcworkspace -scheme IT-EbooksTests

